<div>Mon contact </div>

<form action="/contact/save" method="POST">
	<label for="name">Nom : </label>
	<input type="text" name="name">
	<label for="firstname">Prénom </label>
	<input type="text" name="firstname">
	<input type="submit" value="insert">
</form>

<form action="/contact/extract" method="POST">
	<label for="name">Nom : </label>
	<input type="text" name="name">
	<label for="firstname">Prénom </label>
	<input type="text" name="firstname">
	<input type="submit" value="extract">
</form>

<form action="/contact/extractall" method="POST">
	<input type="submit" value="extract all">
</form>